# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waterName', models.CharField(max_length=50, verbose_name='water_name')),
                ('released', models.BooleanField(default=False, verbose_name='released')),
                ('releasedDate', models.CharField(max_length=20, verbose_name='released_date')),
                ('updateTime', models.DateTimeField(auto_now_add=True, verbose_name='update_time')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
            ],
        ),
    ]
