# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterrecord',
            name='updateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='update_time'),
        ),
    ]
