CREATE TABLE `WATER_MONITOR` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `LOCATION` varchar(256) NOT NULL,
  `START_TIME` varchar(256) NOT NULL,
  `END_TIME` varchar(256) NOT NULL,
  `DURATION` int(11) NOT NULL,
  `RELEASE_DATE` varchar(256) NOT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `UPDATE_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;